/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FifthSection: typeof import('./src/components/fifthSection.vue')['default']
    FirstSection: typeof import('./src/components/firstSection.vue')['default']
    ForthSection: typeof import('./src/components/forthSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondSection: typeof import('./src/components/secondSection.vue')['default']
    ThirdSection: typeof import('./src/components/thirdSection.vue')['default']
  }
}
